export const API_GET_DATASOURCE = 'API_GET_DATASOURCE';

export const API_CREATE_DATASOURCE = 'API_CREATE_DATASOURCE';

export const API_GET_METRICS_BY_DB_ID = 'API_GET_METRICS_BY_DB_ID';

export const API_GET_STATISTICS_BY_METRIC_AND_BETWEEN_DATES =
  'API_GET_STATISTICS_BY_METRIC_AND_BETWEEN_DATES';
