import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.2.1',
  date: '2023-05-29T04:24:05.664Z',
};
export default meta;
